### ISSUE TITLE
implement log mechanism

### ISSUE THREAD

**Issue by shay123g** [mini-services/miniurl#102]
should be:
* write to file / console
* log pattern configurable
* cyclic

@SnirShechter  I tried to search if issue like that already exist and didnt find.. on the other hand I'm still learning the syntax in github so maybe i missed.
something to add?

**Comment by SnirShechter** [comment]
Aviad is working on the logger (I can't tag him here since he didn't confirm the invite yet, but you can find him on Slack).

Basically, we're using the best practices:
* JSON format
* Pretty format in development
* Log level is configurable from the outside

Write to file is an interesting feature, although it's far from the best practices (since Docket implements that himself). We should consider that.

What does cyclic mean? Do you mean that the file is overridden when reaching its size limit?

**Comment by SnirShechter** [comment]
@AviadSofer

**Comment by AviadSofer** [comment]
Hi guys, I am really working on the logge, so thanks.
@shay123g what do you mean by "cyclic'?

**Comment by SnirShechter** [comment]
@shay123g 

Can you comment here? Also, Aviad is already working on it in #21. If these issues overlap, close this one and patch the other.

**Comment by shay123g** [comment]
Cyclic mean rolling file. After reaching certain size, new logfkle created. However i understand now its bad practice for mini service. This is actually overlap with #21 . Closing
